# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: News and Announcements
email: sales@arpnetworks.com
description: > # this means to ignore newlines until "baseurl:"
  The latest from ARP Networks
baseurl: "/news" # the subpath of your site, e.g. /blog
url: "https://arpnetworks.com" # the base hostname & protocol for your site
twitter_username: arpnetworks
github_username:  up_the_irons

# Build settings
markdown: kramdown

twitter:
  username: arpnetworks

gems:
  - jekyll-seo-tag
